<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Currency::insert([
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ALL','title' => 'Albania Lek'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'AFN','title' => 'Afghanistan Afghani'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ARS','title' => 'Argentina Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'AWG','title' => 'Aruba Guilder'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'AUD','title' => 'Australia Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'AZN','title' => 'Azerbaijan New Manat'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BSD','title' => 'Bahamas Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BBD','title' => 'Barbados Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BDT','title' => 'Bangladeshi taka'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BYR','title' => 'Belarus Ruble'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BZD','title' => 'Belize Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BMD','title' => 'Bermuda Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BOB','title' => 'Bolivia Boliviano'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BAM','title' => 'Bosnia and Herzegovina Convertible Marka'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BWP','title' => 'Botswana Pula'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BGN','title' => 'Bulgaria Lev'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BRL','title' => 'Brazil Real'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'BND','title' => 'Brunei Darussalam Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'KHR','title' => 'Cambodia Riel'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CAD','title' => 'Canada Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'KYD','title' => 'Cayman Islands Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CLP','title' => 'Chile Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CNY','title' => 'China Yuan Renminbi'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'COP','title' => 'Colombia Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CRC','title' => 'Costa Rica Colon'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'HRK','title' => 'Croatia Kuna'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CUP','title' => 'Cuba Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CZK','title' => 'Czech Republic Koruna'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'DKK','title' => 'Denmark Krone'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'DOP','title' => 'Dominican Republic Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'XCD','title' => 'East Caribbean Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'EGP','title' => 'Egypt Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SVC','title' => 'El Salvador Colon'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'EEK','title' => 'Estonia Kroon'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'EUR','title' => 'Euro Member Countries'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'FKP','title' => 'Falkland Islands (Malvinas) Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'FJD','title' => 'Fiji Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'GHC','title' => 'Ghana Cedis'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'GIP','title' => 'Gibraltar Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'GTQ','title' => 'Guatemala Quetzal'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'GGP','title' => 'Guernsey Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'GYD','title' => 'Guyana Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'HNL','title' => 'Honduras Lempira'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'HKD','title' => 'Hong Kong Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'HUF','title' => 'Hungary Forint'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ISK','title' => 'Iceland Krona'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'INR','title' => 'India Rupee'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'IDR','title' => 'Indonesia Rupiah'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'IRR','title' => 'Iran Rial'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'IMP','title' => 'Isle of Man Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ILS','title' => 'Israel Shekel'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'JMD','title' => 'Jamaica Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'JPY','title' => 'Japan Yen'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'JEP','title' => 'Jersey Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'KZT','title' => 'Kazakhstan Tenge'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'KPW','title' => 'Korea (North) Won'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'KRW','title' => 'Korea (South) Won'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'KGS','title' => 'Kyrgyzstan Som'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'LAK','title' => 'Laos Kip'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'LVL','title' => 'Latvia Lat'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'LBP','title' => 'Lebanon Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'LRD','title' => 'Liberia Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'LTL','title' => 'Lithuania Litas'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'MKD','title' => 'Macedonia Denar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'MYR','title' => 'Malaysia Ringgit'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'MUR','title' => 'Mauritius Rupee'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'MXN','title' => 'Mexico Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'MNT','title' => 'Mongolia Tughrik'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'MZN','title' => 'Mozambique Metical'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'NAD','title' => 'Namibia Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'NPR','title' => 'Nepal Rupee'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ANG','title' => 'Netherlands Antilles Guilder'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'NZD','title' => 'New Zealand Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'NIO','title' => 'Nicaragua Cordoba'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'NGN','title' => 'Nigeria Naira'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'NOK','title' => 'Norway Krone'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'OMR','title' => 'Oman Rial'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'PKR','title' => 'Pakistan Rupee'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'PAB','title' => 'Panama Balboa'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'PYG','title' => 'Paraguay Guarani'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'PEN','title' => 'Peru Nuevo Sol'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'PHP','title' => 'Philippines Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'PLN','title' => 'Poland Zloty'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'QAR','title' => 'Qatar Riyal'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'RON','title' => 'Romania New Leu'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'RUB','title' => 'Russia Ruble'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SHP','title' => 'Saint Helena Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SAR','title' => 'Saudi Arabia Riyal'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'RSD','title' => 'Serbia Dinar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SCR','title' => 'Seychelles Rupee'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SGD','title' => 'Singapore Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SBD','title' => 'Solomon Islands Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SOS','title' => 'Somalia Shilling'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ZAR','title' => 'South Africa Rand'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'LKR','title' => 'Sri Lanka Rupee'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SEK','title' => 'Sweden Krona'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'CHF','title' => 'Switzerland Franc'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SRD','title' => 'Suriname Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'SYP','title' => 'Syria Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'TWD','title' => 'Taiwan New Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'THB','title' => 'Thailand Baht'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'TTD','title' => 'Trinidad and Tobago Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'TRY','title' => 'Turkey Lira'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'TRL','title' => 'Turkey Lira'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'TVD','title' => 'Tuvalu Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'UAH','title' => 'Ukraine Hryvna'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'GBP','title' => 'United Kingdom Pound'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'USD','title' => 'United States Dollar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'UYU','title' => 'Uruguay Peso'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'UZS','title' => 'Uzbekistan Som'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'VEF','title' => 'Venezuela Bolivar'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'VND','title' => 'Viet Nam Dong'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'YER','title' => 'Yemen Rial'],
                ['uid'=>getRandomCharactor(12,'Currency'),'symbol'=>'ZWD','title' => 'Zimbabwe Dollar']
        
        ]);
    }
}
